<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1 align="center"> About F.A.L.T.U. </h1>
      <p>Fakeerchand and Lakeerchand Trust   University (F.A.L.T.U) is one among the foremost university of national   importance in higher technological education.</p>
      <h3>VISION</h3>
      <p>To be a nationally known   ,reliable,innovative and effective education provider in the emerging   professional disciplines.  The vision of F.A.L.T.U. is to develop, encourage and sustain passion   for learning amongst all the students at the Institute.  It represents   the ultimate     aspirational level for F.A.L.T.U. and  is envisioned as a dynamic,   growth-oriented, world-class professional Institute, providing   futuristic, capacity-enhancing career     options.  We aim to provide, a vibrant learning environment as per   changing needs of the corporate and technical sectors and to rapidly   achieve global benchmarks in     the disciplines of Management, Computer Applications and Journalism and   Mass Communication.</p>
      <h3>MISSION</h3>
      <p>Our core mission is conducting   market-driven undergraduate professional programmes catering to the   chosen disciplines.  It is our mission to provide an integrated     range of academic and career options to students opting to study in our   Institute.  Our mission is to aid the creation of managers who   understand that expertise must     reach corporates, individuals as well as agriculture and the informal   sector.  Also encompassing our mission is the centrality of public   action in the lives of the     Indian citizen.  We view the media and mass communication as vital   instruments in creating the conditions of public action.  Our mission is   to empower student of mass     communication with the required abilities to highlight issues of public   concern, ultimately leading to their solution.  The raison&rsquo;de&rsquo;etre   behind the BCA course is     obvious.  It is our mission to be a part of the information and   knowledge driven economy of the IT enabled age.  In our planning, our   mission is clearly defined in the     following stages.  The first stage deals with capacity creation, with   the ultimate aim of setting standards for academic excellence in the   beginning itself.  We thus     focus on space, technology, faculty and facility creation.    Technological upgradation is the focus and extension of knowledge   grained in the first stage is the core     agenda in the second stage.  Finally, we aim at consolidation of ranking   on the basis of academic and professional expertise.  Academic   excellence will translate into     research &amp; development activities.  In this stage, consolidation of   industry edge and cornering the market are the focus.  This multi-stage   mission is the blue print     for achieving our mission for F.A.L.T.U.  Our core ideal is to undertake   all such activities which may aid in an all round development of   personalities of the students     enabling  them to emerge out products with appropriate mix of   &lsquo;knowledge&rsquo;, &lsquo;skills&rsquo; and &lsquo;attitudes&rsquo;.</p>
</asp:Content>

